working_dir: ./
excludes: ["/.git/", "/datasets/", "/figures/", "/docs/", "/examples/", "/tests/", "*.pyc", "__pycache__"]
env_vars:
  TORCH_NCCL_AVOID_RECORD_STREAMS: "1"
  CUDA_DEVICE_MAX_CONNECTIONS: "1"
  # PYTHONPATH: Update this to your project root path before committing
  PYTHONPATH: "/home/work/cxr/Self-KDRL"
  WANDB_INIT_TIMEOUT: "300"

