working_dir: ./
excludes: ["/.git/", "/datasets/", "/figures/", "/docs/", "/examples/", "/tests/", "*.pyc", "__pycache__"]
env_vars:
  TORCH_NCCL_AVOID_RECORD_STREAMS: "1"
  CUDA_DEVICE_MAX_CONNECTIONS: "1"
  PYTHONPATH: "/home/work/cxr/Self-KDRL"  
